import React, { createContext, useState, useContext } from 'react';

const LanguageContext = createContext();

export const translations = {
    en: {
        // Navigation
        home: 'Home',
        menu: 'Menu',
        orderOnline: 'Order Online',
        gallery: 'Gallery',
        booking: 'Book a Table',
        contact: 'Contact',
        about: 'About Us',

        // Feature
        inclusive: 'Inclusive space',

        // Home Page
        heroTitle: 'Welcome to Oslo Sushi',
        heroSubtitle: 'Authentic Japanese dining in Gijón, Spain',
        viewMenu: 'View Menu',
        whatOurCustomersSay: 'What Our Customers Say',
        customerReviewsSubtitle: "Hear from those who've experienced our hospitality",
        verifiedCustomer: 'Verified Customer',
        leaveReview: 'Leave a Review',
        todaysSpecial: "Today's Special",
        todaysSpecialSubtitle: 'Fresh seasonal dishes crafted daily',
        lgbtqFriendly: 'LGBTQ Friendly',
        topRated: 'Top Rated',
        topRatedSubtitle: '4.5 Stars (500+ Reviews)',
        easyBooking: 'Easy Booking',
        easyBookingSubtitle: 'Reserve your table online',
        orderOnlineSubtitle: 'Pickup & Delivery',
        whyUs: 'Why Us?',
        sushiArtExperience: 'Experience the Art of Sushi in Gijón',
        whyUsP1: 'At Oslo Sushi, we believe that great food allows you to experience culture. Our dedicated chefs bring years of experience and passion to every roll, ensuring that each bite is a journey through authentic Japanese flavors.',
        whyUsP2: "We pride ourselves on using only the freshest, high-quality ingredients. Whether you're a vegan sushi lover or a traditional sashimi enthusiast, our diverse menu is crafted to cater to every palate while maintaining the highest standards of culinary excellence.",
        whyUsP3: 'Beyond the food, we strive to create a warm, inclusive atmosphere where everyone feels welcome. Join us for a memorable dining experience that combines tradition, innovation, and genuine hospitality.',
        readyToDine: 'Ready to Dine With Us?',
        bookTableToday: 'Book your table today and experience the finest Japanese cuisine in Gijón',
        reserveYourTable: 'Reserve Your Table',

        // Footer
        osloSushiDescription: 'Authentic Japanese cuisine in the heart of Gijón, Spain. Experience exquisite sushi and traditional dishes crafted with passion.',
        contactUs: 'Contact Us',
        openingHours: 'Opening Hours',
        everyDay: 'Every Day:',
        opensAt: 'Opens 8:00 PM',
        deliveryTakeout: 'Delivery & Takeout:',
        available: 'Available',
        rightsReserved: 'Restaurante Japonés Oslo Sushi. All rights reserved.',
        reservations: 'Reservations',

        // About Page
        traditionMeetsInnovation: 'Tradition Meets Innovation',
        aboutP1: 'Founded in 2020, Oslo Sushi began with a simple vision: to bring authentic, high-quality Japanese cuisine to the heart of Gijón. We believed that sushi is more than just food; it\'s an art form that requires patience, precision, and respect for ingredients.',
        aboutP2: 'Our name, "Oslo Sushi," reflects our unique approach – blending the minimalist, clean aesthetics of Scandinavian design with the intricate, flavor-rich traditions of Japan. It represents a fusion of cultures, prioritizing freshness, simplicity, and elegance in every dish.',
        aboutP3: 'Over the years, we have grown from a small takeaway spot to a beloved dining destination. We are proud to serve our community with dishes that honor traditional techniques while embracing modern creativity.',
        yearsOfExcellence: 'Years of Excellence',
        ourCoreValues: 'Our Core Values',
        coreValuesSubtitle: 'These principles guide every decision we make, from the ingredients we source to the way we serve you.',
        qualityFirst: 'Quality First',
        qualityFirstDesc: 'We source only the freshest, premium-grade fish and locally grown vegetables.',
        community: 'Community',
        communityDesc: 'We treat our guests and staff like family, fostering a warm, inclusive environment.',
        craftsmanship: 'Craftsmanship',
        craftsmanshipDesc: 'Every roll is hand-crafted with meticulous attention to detail and balance.',
        passion: 'Passion',
        passionDesc: 'We love what we do, and that passion shines through in every bite.',
        meetOurChefs: 'Meet Our Chefs',
        meetOurChefsSubtitle: 'The masters behind your favorite dishes.',
        executiveChef: 'Executive Chef',
        sushiSpecialist: 'Sushi Specialist',
        hotKitchenLead: 'Hot Kitchen Lead',

        // Order Online Page
        orderOnlineTitle: 'Order Online',
        orderOnlineHeroSubtitle: 'Enjoy Oslo Sushi in the comfort of your home',
        howToReceiveOrder: 'How would you like to receive your order?',
        delivery: 'Delivery',
        pickup: 'Pickup',
        estimatedTime: 'Estimated Time',
        location: 'Location',
        firstOrderDiscount: 'First Order Discount',
        firstOrderDiscountText: 'Get 10% off your first online order with code:',
        browseMenu: 'Browse Menu',
        starters: 'Starters',
        sushiRolls: 'Sushi Rolls',
        nigiriSashimi: 'Nigiri & Sashimi',
        mainDishes: 'Main Dishes',
        readyToOrder: 'Ready to Order?',
        platformNote: 'We use our trusted partners for secure online ordering and delivery tracking.',
        orderOnGlovo: 'Order on Glovo',
        orderOnUberEats: 'Order on UberEats',

        // Booking Page
        bookTableTitle: 'Book a Table',
        bookTableSubtitle: 'Reserve your spot for an unforgettable dining experience',

        // Contact Page
        getInTouch: 'Get in Touch',
        contactSubtitle: 'Have questions or want to make a reservation? We\'re here to help.',
        address: 'Address',
        phone: 'Phone',
        email: 'Email',
        openingHoursTitle: 'Opening Hours',
        mondaySunday: 'Monday - Sunday',
        sendMessage: 'Send us a Message',
        yourName: 'Your Name',
        yourEmail: 'Your Email',
        subject: 'Subject',
        message: 'Message',
        submit: 'Send Message',
    },
    es: {
        // Navegación
        home: 'Inicio',
        menu: 'Menú',
        orderOnline: 'Pedir Online',
        gallery: 'Galería',
        booking: 'Reservar Mesa',
        contact: 'Contacto',
        about: 'Sobre Nosotros',

        // Feature
        inclusive: 'Espacio inclusivo',

        // Página de Inicio
        heroTitle: 'Bienvenido a Oslo Sushi',
        heroSubtitle: 'Auténtica cocina japonesa en Gijón, España',
        viewMenu: 'Ver Menú',
        whatOurCustomersSay: 'Lo que dicen nuestros clientes',
        customerReviewsSubtitle: 'Escuche a quienes han experimentado nuestra hospitalidad',
        verifiedCustomer: 'Cliente Verificado',
        leaveReview: 'Dejar una Reseña',
        todaysSpecial: 'Especial de Hoy',
        todaysSpecialSubtitle: 'Platos frescos de temporada creados a diario',
        lgbtqFriendly: 'LGBTQ Friendly',
        topRated: 'Mejor Valorado',
        topRatedSubtitle: '4.5 Estrellas (500+ Reseñas)',
        easyBooking: 'Reserva Fácil',
        easyBookingSubtitle: 'Reserva tu mesa online',
        orderOnlineSubtitle: 'Recogida y Entrega',
        whyUs: '¿Por qué Nosotros?',
        sushiArtExperience: 'Experimenta el Arte del Sushi en Gijón',
        whyUsP1: 'En Oslo Sushi, creemos que la buena comida te permite experimentar la cultura. Nuestros dedicados chefs aportan años de experiencia y pasión a cada rollo, asegurando que cada bocado sea un viaje a través de auténticos sabores japoneses.',
        whyUsP2: 'Nos enorgullecemos de utilizar solo los ingredientes más frescos y de alta calidad. Ya sea que seas un amante del sushi vegano o un entusiasta del sashimi tradicional, nuestro menú diverso está diseñado para satisfacer todos los paladares manteniendo los más altos estándares de excelencia culinaria.',
        whyUsP3: 'Más allá de la comida, nos esforzamos por crear un ambiente cálido e inclusivo donde todos se sientan bienvenidos. Únete a nosotros para una experiencia gastronómica memorable que combina tradición, innovación y hospitalidad genuina.',
        readyToDine: '¿Listo para cenar con nosotros?',
        bookTableToday: 'Reserva tu mesa hoy y experimenta la mejor cocina japonesa en Gijón',
        reserveYourTable: 'Reserva Tu Mesa',

        // Pie de página
        osloSushiDescription: 'Auténtica cocina japonesa en el corazón de Gijón, España. Experimenta sushi exquisito y platos tradicionales elaborados con pasión.',
        contactUs: 'Contáctanos',
        openingHours: 'Horario de Apertura',
        everyDay: 'Todos los días:',
        opensAt: 'Abre a las 20:00',
        deliveryTakeout: 'Entrega y Para Llevar:',
        available: 'Disponible',
        rightsReserved: 'Restaurante Japonés Oslo Sushi. Todos los derechos reservados.',
        reservations: 'Reservas',

        // Página Sobre Nosotros
        traditionMeetsInnovation: 'Tradición e Innovación',
        aboutP1: 'Fundado en 2020, Oslo Sushi comenzó con una visión simple: traer auténtica cocina japonesa de alta calidad al corazón de Gijón. Creíamos que el sushi es más que comida; es una forma de arte que requiere paciencia, precisión y respeto por los ingredientes.',
        aboutP2: 'Nuestro nombre, "Oslo Sushi", refleja nuestro enfoque único: mezclar la estética minimalista y limpia del diseño escandinavo con las intrincadas y ricas tradiciones de Japón. Representa una fusión de culturas, priorizando la frescura, la simplicidad y la elegancia en cada plato.',
        aboutP3: 'A lo largo de los años, hemos pasado de ser un pequeño lugar de comida para llevar a un destino gastronómico querido. Estamos orgullosos de servir a nuestra comunidad con platos que honran las técnicas tradicionales mientras abrazan la creatividad moderna.',
        yearsOfExcellence: 'Años de Excelencia',
        ourCoreValues: 'Nuestros Valores',
        coreValuesSubtitle: 'Estos principios guían cada decisión que tomamos, desde los ingredientes que obtenemos hasta la forma en que te servimos.',
        qualityFirst: 'Calidad Primero',
        qualityFirstDesc: 'Obtenemos solo el pescado más fresco de primera calidad y verduras cultivadas localmente.',
        community: 'Comunidad',
        communityDesc: 'Tratamos a nuestros huéspedes y personal como familia, fomentando un ambiente cálido e inclusivo.',
        craftsmanship: 'Artesanía',
        craftsmanshipDesc: 'Cada rollo está hecho a mano con meticulosa atención al detalle y equilibrio.',
        passion: 'Pasión',
        passionDesc: 'Amamos lo que hacemos, y esa pasión brilla en cada bocado.',
        meetOurChefs: 'Conoce a Nuestros Chefs',
        meetOurChefsSubtitle: 'Los maestros detrás de tus platos favoritos.',
        executiveChef: 'Chef Ejecutivo',
        sushiSpecialist: 'Especialista en Sushi',
        hotKitchenLead: 'Jefe de Cocina Caliente',

        // Página Pedir Online
        orderOnlineTitle: 'Pedir Online',
        orderOnlineHeroSubtitle: 'Disfruta de Oslo Sushi en la comodidad de tu hogar',
        howToReceiveOrder: '¿Cómo te gustaría recibir tu pedido?',
        delivery: 'Entrega a domicilio',
        pickup: 'Recogida',
        estimatedTime: 'Tiempo Estimado',
        location: 'Ubicación',
        firstOrderDiscount: 'Descuento Primer Pedido',
        firstOrderDiscountText: 'Obtén 10% de dto. en tu primer pedido online con el código:',
        browseMenu: 'Explorar Menú',
        starters: 'Entrantes',
        sushiRolls: 'Rollos de Sushi',
        nigiriSashimi: 'Nigiri y Sashimi',
        mainDishes: 'Platos Principales',
        readyToOrder: '¿Listo para pedir?',
        platformNote: 'Utilizamos nuestros socios de confianza para pedidos online seguros y seguimiento de entrega.',
        orderOnGlovo: 'Pedir en Glovo',
        orderOnUberEats: 'Pedir en UberEats',

        // Booking Page
        bookTableTitle: 'Reservar una Mesa',
        bookTableSubtitle: 'Reserva tu lugar para una experiencia gastronómica inolvidable',

        // Contact Page
        getInTouch: 'Ponte en Contacto',
        contactSubtitle: '¿Tienes preguntas o quieres hacer una reserva? Estamos aquí para ayudar.',
        address: 'Dirección',
        phone: 'Teléfono',
        email: 'Correo Electrónico',
        openingHoursTitle: 'Horario',
        mondaySunday: 'Lunes - Domingo',
        sendMessage: 'Envíanos un Mensaje',
        yourName: 'Tu Nombre',
        yourEmail: 'Tu Email',
        subject: 'Asunto',
        message: 'Mensaje',
        submit: 'Enviar Mensaje',
    },
    fr: {
        // Navigation
        home: 'Accueil',
        menu: 'Menu',
        orderOnline: 'Commander',
        gallery: 'Galerie',
        booking: 'Réserver',
        contact: 'Contact',
        about: 'À Propos',

        // Feature
        inclusive: 'Espace inclusif',

        // Page d'Accueil
        heroTitle: 'Bienvenue chez Oslo Sushi',
        heroSubtitle: 'Cuisine japonaise authentique à Gijón, Espagne',
        viewMenu: 'Voir le Menu',
        whatOurCustomersSay: 'Ce que disent nos clients',
        customerReviewsSubtitle: 'Découvrez les avis de ceux qui ont goûté à notre hospitalité',
        verifiedCustomer: 'Client Vérifié',
        leaveReview: 'Laisser un Avis',
        todaysSpecial: 'Spécial du Jour',
        todaysSpecialSubtitle: 'Plats de saison frais créés chaque jour',
        lgbtqFriendly: 'LGBTQ Friendly',
        topRated: 'Mieux Noté',
        topRatedSubtitle: '4.5 Étoiles (500+ Avis)',
        easyBooking: 'Réservation Facile',
        easyBookingSubtitle: 'Réservez votre table en ligne',
        orderOnlineSubtitle: 'Emporter et Livraison',
        whyUs: 'Pourquoi Nous ?',
        sushiArtExperience: "Découvrez l'Art du Sushi à Gijón",
        whyUsP1: "Chez Oslo Sushi, nous croyons que la bonne cuisine vous permet de découvrir la culture. Nos chefs dévoués apportent des années d'expérience et de passion à chaque rouleau, garantissant que chaque bouchée soit un voyage à travers des saveurs japonaises authentiques.",
        whyUsP2: "Nous sommes fiers d'utiliser uniquement les ingrédients les plus frais et de haute qualité. Que vous soyez un amateur de sushis véganes ou un passionné de sashimis traditionnels, notre menu varié est conçu pour satisfaire tous les palais tout en maintenant les plus hauts standards d'excellence culinaire.",
        whyUsP3: "Au-delà de la nourriture, nous nous efforçons de créer une atmosphère chaleureuse et inclusive où chacun se sent le bienvenu. Rejoignez-nous pour une expérience culinaire mémorable alliant tradition, innovation et hospitalité sincère.",
        readyToDine: 'Prêt à dîner avec nous ?',
        bookTableToday: 'Réservez votre table aujourd\'hui et découvrez la meilleure cuisine japonaise de Gijón',
        reserveYourTable: 'Réservez Votre Table',

        // Pied de page
        osloSushiDescription: 'Cuisine japonaise authentique au cœur de Gijón, en Espagne. Dégustez des sushis exquis et des plats traditionnels préparés avec passion.',
        contactUs: 'Contactez-nous',
        openingHours: 'Heures d\'ouverture',
        everyDay: 'Tous les jours :',
        opensAt: 'Ouvre à 20h00',
        deliveryTakeout: 'Livraison et à emporter :',
        available: 'Disponible',
        rightsReserved: 'Restaurant Japonais Oslo Sushi. Tous droits réservés.',
        reservations: 'Réservations',

        // Page À Propos
        traditionMeetsInnovation: 'Tradition et Innovation',
        aboutP1: 'Fondé en 2020, Oslo Sushi a commencé avec une vision simple : apporter une cuisine japonaise authentique et de haute qualité au cœur de Gijón. Nous croyions que le sushi est plus qu\'un simple aliment ; c\'est une forme d\'art qui nécessite patience, précision et respect des ingrédients.',
        aboutP2: 'Notre nom, "Oslo Sushi", reflète notre approche unique : mélanger l\'esthétique minimaliste et épurée du design scandinave avec les traditions complexes et riches en saveurs du Japon. Il représente une fusion de cultures, privilégiant la fraîcheur, la simplicité et l\'élégance dans chaque plat.',
        aboutP3: 'Au fil des ans, nous sommes passés d\'un petit lieu de vente à emporter à une destination gastronomique appréciée. Nous sommes fiers de servir notre communauté avec des plats qui honorent les techniques traditionnelles tout en embrassant la créativité moderne.',
        yearsOfExcellence: 'Années d\'Excellence',
        ourCoreValues: 'Nos Valeurs',
        coreValuesSubtitle: 'Ces principes guident chaque décision que nous prenons, des ingrédients que nous sourçons à la façon dont nous vous servons.',
        qualityFirst: 'Qualité d\'Abord',
        qualityFirstDesc: 'Nous ne fournissons que du poisson de première qualité et des légumes cultivés localement.',
        community: 'Communauté',
        communityDesc: 'Nous traitons nos invités et notre personnel comme de la famille, favorisant un environnement chaleureux et inclusif.',
        craftsmanship: 'Savoir-faire',
        craftsmanshipDesc: 'Chaque rouleau est fabriqué à la main avec une attention méticuleuse aux détails et à l\'équilibre.',
        passion: 'Passion',
        passionDesc: 'Nous aimons ce que nous faisons, et cette passion transparaît dans chaque bouchée.',
        meetOurChefs: 'Rencontrez Nos Chefs',
        meetOurChefsSubtitle: 'Les maîtres derrière vos plats préférés.',
        executiveChef: 'Chef Exécutif',
        sushiSpecialist: 'Spécialiste Sushi',
        hotKitchenLead: 'Chef de Cuisine Chaude',

        // Page Commander en Ligne
        orderOnlineTitle: 'Commander en Ligne',
        orderOnlineHeroSubtitle: 'Profitez d\'Oslo Sushi dans le confort de votre maison',
        howToReceiveOrder: 'Comment souhaitez-vous recevoir votre commande ?',
        delivery: 'Livraison',
        pickup: 'À emporter',
        estimatedTime: 'Temps Estimé',
        location: 'Lieu',
        firstOrderDiscount: 'Réduction Première Commande',
        firstOrderDiscountText: 'Obtenez 10% de réduction sur votre première commande en ligne avec le code :',
        browseMenu: 'Parcourir le Menu',
        starters: 'Entrées',
        sushiRolls: 'Rouleaux de Sushi',
        nigiriSashimi: 'Nigiri et Sashimi',
        mainDishes: 'Plats Principaux',
        readyToOrder: 'Prêt à commander ?',
        platformNote: 'Nous utilisons nos partenaires de confiance pour la commande en ligne sécurisée et le suivi de la livraison.',
        orderOnGlovo: 'Commander sur Glovo',
        orderOnUberEats: 'Commander sur UberEats',

        // Booking Page
        bookTableTitle: 'Réserver une Table',
        bookTableSubtitle: 'Réservez votre place pour une expérience culinaire inoubliable',

        // Contact Page
        getInTouch: 'Entrer en Contact',
        contactSubtitle: 'Vous avez des questions ou souhaitez faire une réservation ? Nous sommes là pour vous aider.',
        address: 'Adresse',
        phone: 'Téléphone',
        email: 'Email',
        openingHoursTitle: 'Heures d\'ouverture',
        mondaySunday: 'Lundi - Dimanche',
        sendMessage: 'Envoyez-nous un Message',
        yourName: 'Votre Nom',
        yourEmail: 'Votre Email',
        subject: 'Sujet',
        message: 'Message',
        submit: 'Envoyer le Message',
    },
    de: {
        // Navigation
        home: 'Startseite',
        menu: 'Speisekarte',
        orderOnline: 'Bestellen',
        gallery: 'Galerie',
        booking: 'Reservieren',
        contact: 'Kontakt',
        about: 'Über Uns',

        // Feature
        inclusive: 'Inklusiver Raum',

        // Startseite
        heroTitle: 'Willkommen bei Oslo Sushi',
        heroSubtitle: 'Authentische japanische Küche in Gijón, Spanien',
        viewMenu: 'Speisekarte Ansehen',
        whatOurCustomersSay: 'Was unsere Kunden sagen',
        customerReviewsSubtitle: 'Hören Sie von denen, die unsere Gastfreundschaft erlebt haben',
        verifiedCustomer: 'Verifizierter Kunde',
        leaveReview: 'Bewertung Hinterlassen',
        todaysSpecial: 'Tagesangebot',
        todaysSpecialSubtitle: 'Frische saisonale Gerichte, täglich zubereitet',
        lgbtqFriendly: 'LGBTQ Freundlich',
        topRated: 'Bestbewertet',
        topRatedSubtitle: '4,5 Sterne (500+ Bewertungen)',
        easyBooking: 'Einfache Buchung',
        easyBookingSubtitle: 'Reservieren Sie Ihren Tisch online',
        orderOnlineSubtitle: 'Abholung & Lieferung',
        whyUs: 'Warum Wir?',
        sushiArtExperience: 'Erleben Sie die Kunst des Sushi in Gijón',
        whyUsP1: 'Bei Oslo Sushi glauben wir, dass gutes Essen es Ihnen ermöglicht, Kultur zu erleben. Unsere engagierten Köche bringen jahrelange Erfahrung und Leidenschaft in jede Rolle ein und sorgen dafür, dass jeder Bissen eine Reise durch authentische japanische Aromen ist.',
        whyUsP2: 'Wir sind stolz darauf, nur die frischesten und hochwertigsten Zutaten zu verwenden. Egal, ob Sie ein Liebhaber von veganem Sushi oder ein Enthusiast von traditionellem Sashimi sind, unser vielfältiges Menü ist darauf ausgelegt, jedem Gaumen gerecht zu werden und gleichzeitig die höchsten Standards kulinarischer Exzellenz zu wahren.',
        whyUsP3: 'Jenseits des Essens bemühen wir uns, eine warme, inklusive Atmosphäre zu schaffen, in der sich jeder willkommen fühlt. Begleiten Sie uns zu einem unvergesslichen kulinarischen Erlebnis, das Tradition, Innovation und echte Gastfreundschaft verbindet.',
        readyToDine: 'Bereit, bei uns zu essen?',
        bookTableToday: 'Reservieren Sie noch heute Ihren Tisch und erleben Sie die feinste japanische Küche in Gijón',
        reserveYourTable: 'Tisch Reservieren',

        // Fußzeile
        osloSushiDescription: 'Authentische japanische Küche im Herzen von Gijón, Spanien. Erleben Sie exquisites Sushi und traditionelle Gerichte, die mit Leidenschaft zubereitet werden.',
        contactUs: 'Kontaktieren Sie uns',
        openingHours: 'Öffnungszeiten',
        everyDay: 'Jeden Tag:',
        opensAt: 'Öffnet um 20:00 Uhr',
        deliveryTakeout: 'Lieferung & Abholung:',
        available: 'Verfügbar',
        rightsReserved: 'Japanisches Restaurant Oslo Sushi. Alle Rechte vorbehalten.',
        reservations: 'Reservierungen',

        // Über Uns Seite
        traditionMeetsInnovation: 'Tradition trifft Innovation',
        aboutP1: 'Gegründet im Jahr 2020, begann Oslo Sushi mit einer einfachen Vision: authentische, hochwertige japanische Küche ins Herz von Gijón zu bringen. Wir glaubten, dass Sushi mehr ist als nur Essen; es ist eine Kunstform, die Geduld, Präzision und Respekt vor den Zutaten erfordert.',
        aboutP2: 'Unser Name "Oslo Sushi" spiegelt unseren einzigartigen Ansatz wider – die minimalistische, saubere Ästhetik des skandinavischen Designs mit den komplexen, geschmacksintensiven Traditionen Japans zu verbinden. Er steht für eine Verschmelzung der Kulturen, wobei Frische, Einfachheit und Eleganz in jedem Gericht im Vordergrund stehen.',
        aboutP3: 'Im Laufe der Jahre haben wir uns von einem kleinen Imbiss zu einem beliebten Speiselokal entwickelt. Wir sind stolz darauf, unserer Gemeinschaft Gerichte zu servieren, die traditionelle Techniken ehren und gleichzeitig moderne Kreativität umarmen.',
        yearsOfExcellence: 'Jahre der Exzellenz',
        ourCoreValues: 'Unsere Grundwerte',
        coreValuesSubtitle: 'Diese Prinzipien leiten jede Entscheidung, die wir treffen, von den Zutaten, die wir beziehen, bis hin zur Art und Weise, wie wir Sie bedienen.',
        qualityFirst: 'Qualität Zuerst',
        qualityFirstDesc: 'Wir beziehen nur den frischesten Fisch in Premiumqualität und lokal angebautes Gemüse.',
        community: 'Gemeinschaft',
        communityDesc: 'Wir behandeln unsere Gäste und Mitarbeiter wie Familie und fördern eine warme, inklusive Umgebung.',
        craftsmanship: 'Handwerkskunst',
        craftsmanshipDesc: 'Jede Rolle wird mit akribischer Aufmerksamkeit für Details und Balance handgefertigt.',
        passion: 'Leidenschaft',
        passionDesc: 'Wir lieben, was wir tun, und diese Leidenschaft strahlt in jedem Bissen.',
        meetOurChefs: 'Treffen Sie Unsere Köche',
        meetOurChefsSubtitle: 'Die Meister hinter Ihren Lieblingsgerichten.',
        executiveChef: 'Chefkoch',
        sushiSpecialist: 'Sushi-Spezialist',
        hotKitchenLead: 'Leiter der Warmen Küche',

        // Online Bestellen Seite
        orderOnlineTitle: 'Online Bestellen',
        orderOnlineHeroSubtitle: 'Genießen Sie Oslo Sushi bequem von zu Hause aus',
        howToReceiveOrder: 'Wie möchten Sie Ihre Bestellung erhalten?',
        delivery: 'Lieferung',
        pickup: 'Abholung',
        estimatedTime: 'Geschätzte Zeit',
        location: 'Standort',
        firstOrderDiscount: 'Rabatt auf erste Bestellung',
        firstOrderDiscountText: 'Erhalten Sie 10% Rabatt auf Ihre erste Online-Bestellung mit dem Code:',
        browseMenu: 'Menü Durchstöbern',
        starters: 'Vorspeisen',
        sushiRolls: 'Sushi-Rollen',
        nigiriSashimi: 'Nigiri & Sashimi',
        mainDishes: 'Hauptgerichte',
        readyToOrder: 'Bereit zu bestellen?',
        platformNote: 'Wir nutzen unsere vertrauenswürdigen Partner für sichere Online-Bestellungen und Lieferverfolgung.',
        orderOnGlovo: 'Bei Glovo bestellen',
        orderOnUberEats: 'Bei UberEats bestellen',

        // Booking Page
        bookTableTitle: 'Tisch Reservieren',
        bookTableSubtitle: 'Sichern Sie sich Ihren Platz für ein unvergessliches kulinarisches Erlebnis',

        // Contact Page
        getInTouch: 'Kontakt Aufnehmen',
        contactSubtitle: 'Haben Sie Fragen oder möchten Sie reservieren? Wir sind hier, um zu helfen.',
        address: 'Adresse',
        phone: 'Telefon',
        email: 'E-Mail',
        openingHoursTitle: 'Öffnungszeiten',
        mondaySunday: 'Montag - Sonntag',
        sendMessage: 'Nachricht Senden',
        yourName: 'Ihr Name',
        yourEmail: 'Ihre E-Mail',
        subject: 'Betreff',
        message: 'Nachricht',
        submit: 'Nachricht Senden',
    }
};

export const LanguageProvider = ({ children }) => {
    const [language, setLanguage] = useState('es'); // Default to Spanish as requested

    const t = (key) => {
        return translations[language][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => useContext(LanguageContext);
